apiVersion: v1
kind: ConfigMap
metadata:
  name: vr-function
data:
  FUNCTIONS_WORKER_RUNTIME: "dotnet"
  ApproverEmail: "__{APPROVER_MAIL}__"
  SenderEmail: "__{SENDER_MAIL}__"
  AzureWebJobsSecretStorageType: "files"
  Host: "https://__{ProjectName}__WebDev.azurewebsites.net"
---
apiVersion: v1
kind: Secret
metadata:
  name: vr-function-secrets
  namespace: __{Namespace}__
type: Opaque
stringData:
  value: "{
    \"APPINSIGHTS_INSTRUMENTATIONKEY\": \"__{ApplicationInsightsInstrumentationKey}__\",
    \"SendGridKey\": \"__{SendGridKey}__\",
    \"AzureWebJobsStorage\": \"__{StorageConnectionString}__\",
    \"AzureWebJobsDashboard\": \"__{StorageConnectionString}__\"
  }"
