AZURE_SUBSCRIPTION_ID = "__SubscriptionId__"
AZURE_TENANT_ID = "__TenantId__"
PROJECT_NAME = "__ProjectName__"
RESOURCE_GROUP_LOCATION = "__ResourceGroupLocation__"
APP_INSIGHTS_PROJECT_TYPE = "__ApplicationInsightsProjectType__"